//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turma
    {
        public int Id { get; set; }
        public string Sala { get; set; }
        public string Quantidade { get; set; }
        public string Turno { get; set; }
        public int AlunoId { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Aluno Aluno { get; set; }
    }
}
